"""Contratos Pydantic compartidos — secciones 3.3 y 3.8 del Technical Brief v2."""

from .caso import (
    Caso,
    ContextManagerInput,
    ContextoComprimido,
    EstadoCaso,
    TipoAccion,
)
from .documento import (
    Documento,
    DocumentoCreate,
    DocumentoExtracto,
    EstadoDocumento,
    ExtractorInput,
    ExtractorOutput,
    FechaDetectada,
    ParteDetectada,
    RolParte,
)
from .fase_output import (
    AdversarialInput,
    AdversarialOutput,
    Correccion,
    DireccionFactor,
    EstadoVerificacionCita,
    Factor,
    FaseCodigo,
    FaseOutput,
    FuenteVerificacionCita,
    JurisprudenciaInput,
    JurisprudenciaOutput,
    LumiCoreInput,
    LumiCoreResponse,
    PrioridadCorreccion,
    ProbabilisticInput,
    ProbabilisticOutput,
    QAInput,
    QAOutput,
    SemaforoQA,
    VerificacionCita,
    WordGeneratorInput,
    WordOutput,
)
from .hecho import EstatusEpistemico, Hecho

__all__ = [
    "AdversarialInput",
    "AdversarialOutput",
    "Caso",
    "ContextManagerInput",
    "ContextoComprimido",
    "Correccion",
    "DireccionFactor",
    "Documento",
    "DocumentoCreate",
    "DocumentoExtracto",
    "EstadoCaso",
    "EstadoDocumento",
    "EstadoVerificacionCita",
    "EstatusEpistemico",
    "ExtractorInput",
    "ExtractorOutput",
    "Factor",
    "FaseCodigo",
    "FaseOutput",
    "FechaDetectada",
    "FuenteVerificacionCita",
    "Hecho",
    "JurisprudenciaInput",
    "JurisprudenciaOutput",
    "LumiCoreInput",
    "LumiCoreResponse",
    "ParteDetectada",
    "PrioridadCorreccion",
    "ProbabilisticInput",
    "ProbabilisticOutput",
    "QAInput",
    "QAOutput",
    "RolParte",
    "SemaforoQA",
    "TipoAccion",
    "VerificacionCita",
    "WordGeneratorInput",
    "WordOutput",
]
